name: neural-sculpture
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.0.221
  - ffmpeg=4.3.2
  - imageio=2.9.0
  - jpeg=9d
  - mkl=2020.4
  - ninja=1.10.2
  - numpy=1.21.0
  - pillow=8.3.1
  - pip=21.0.1
  - python=3.7.9
  - yapf=0.31.0
  - pip:
    - trimesh==3.9.29
    - fastapi==0.68.1
    - uvicorn==0.15.0
    - scikit_image==0.18.3
    - absl-py==0.13.0
    - aiohttp==3.7.4.post0
    - async-timeout==3.0.1
    - attrs==21.2.0
    - blobfile==1.2.3
    - build==0.5.1
    - cachetools==4.2.2
    - chardet==4.0.0
    - clip-by-openai==0.1.1.5
    - colorama==0.4.4
    - dall-e==0.1
    - docutils==0.17.1
    - einops==0.3.0
    - filelock==3.0.12
    - fsspec==2021.6.1
    - ftfy==6.0.3
    - google-auth==1.32.1
    - google-auth-oauthlib==0.4.4
    - grpcio==1.38.1
    - hugging-gan-test==0.0.7
    - idna==2.10
    - imageio-ffmpeg==0.4.3
    - importlib-metadata==4.6.1
    - iniconfig==1.1.1
    - markdown==3.3.4
    - multidict==5.1.0
    - mypy==0.910
    - mypy-extensions==0.4.3
    - oauthlib==3.1.1
    - omegaconf==2.0.6
    - packaging==21.0
    - pep517==0.11.0
    - pluggy==0.13.1
    - protobuf==3.17.3
    - py==1.10.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycryptodomex==3.10.1
    - pydeprecate==0.3.0
    - pyparsing==2.4.7
    - pytest==6.2.4
    - pytorch-lightning==1.3.3
    - pyyaml==5.4.1
    - regex==2021.7.6
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - six==1.16.0
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - toml==0.10.2
    - tomli==1.0.4
    - torch==1.7.1
    - torchmetrics==0.4.1
    - torchvision==0.8.2
    - tqdm==4.60.0
    - twine==3.4.2
    - typed-ast==1.4.3
    - urllib3==1.26.6
    - wcwidth==0.2.5
    - werkzeug==2.0.1
    - xmltodict==0.12.0
    - yarl==1.6.3
    - zipp==3.5.0
    - jupyterlab==3.1.4

