wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.9
    start_time: 1629939570
    t:
      1:
      - 1
      4: 3.7.9
      5: 0.12.0
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 16
camera:
  desc: null
  value: namespace(init_num_cameras=16, mapping_span=6.283185307179586, mapping_type='sdfdiff',
    max_num_cameras=32, shuffle_order=True)
init_tolerance:
  desc: null
  value: 0
iters_per_res:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.03
loss:
  desc: null
  value: namespace(image_loss_weight=0.0002, lp_loss_weight=0.001, sdf_loss_weight=0.001)
max_iters_per_cam:
  desc: null
  value: 32
